In [1]:
# numpy is used for scintific caliculations with many usefull functions 
# it is basis for pandas
# agenda:
    # basics and array creation 
    # indexing and slicing
    # basic operations 
    # universal functions

In [2]:
# numpy array is similar to a list 
# its usually fixed in size & each element is of same type
import numpy as np # import module

In [4]:
# creation of numpy array
# 1st way of creating numpy array is casting a list into numpy array
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [6]:
type(a) # check if its numpy array

numpy.ndarray

In [12]:
a.dtype # used to check elements data type in numpy arrays

dtype('int32')

In [13]:
# accessing elements
a[0]

1

In [15]:
# size of array
a.size

4

In [17]:
# to know no.of dimensions or rank of array we use .ndim
a.ndim

1

In [18]:
# to know size of array in each dimension we use .shape
a.shape

(4,)

In [20]:
# updating ele in array
a[0] = 12
a

array([12,  2,  3,  4])

In [21]:
# slicing array
a[1:]

array([2, 3, 4])

In [22]:
# strid in arrays
a[::2]

array([12,  3])

In [25]:
# basic operations
# 1. vector addition and subtraction
u = np.array([0,1])
v = np.array([1,0])
z = u+v
print("vector addition: ",z)
z = u-v
print("vector sub: ",z)

vector addition:  [1 1]
vector sub:  [-1  1]


In [26]:
# vector multiplication with scalar
y = 2*z
print("scalar mul : ",y)

scalar mul :  [-2  2]


In [27]:
# multiplication of two vectors
x = u*v
print("multiplication of u and v : ",x)

multiplication of u and v :  [0 0]


In [29]:
# dot product of two vectors
# eg dot product of z and y is zTy --> T is transpose
print("z is :",z)
print("y is :",y)
# -1*-2 + 1*2
x = np.dot(z,y)
print("dot product of z and y is: ",x)

z is : [-1  1]
y is : [-2  2]
dot product of z and y is:  4


In [30]:
# adding constant to an array
# z+1 => [-1+1,1+1]
x = z+1
print("answer is : ",x)

answer is :  [0 2]


In [31]:
# universal function is a function that can be applied for an N D array
# 1. caliculate mean of al elements of array we use .mean()
x.mean()

1.0

In [33]:
# 2. to find max value in array we use
x.max()

2

In [34]:
# 3. to find min value in array we use
x.min()

0

In [35]:
# we can access pi value directly by np.pi
np.pi

3.141592653589793

In [38]:
# x = [0,pi/2,pi/3] is done as below
x = [0,np.pi/2,np.pi/3]

In [39]:
# we can apply sin function to all vaues of x directly like below
y = np.sin(x) # => [sin(0),sin(pi/2),sin(pi/3)]

In [44]:
np.linspace(-2,2,5) # linspace is used to create an array with starting point -2 and ending point 2 with no.of elements 5
# no.of elements determines the equal spacing between the numbers

array([-2., -1.,  0.,  1.,  2.])

In [45]:
np.linspace(-2,2,9)

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])