In [3]:
# table of contents
    # 1. basics and array creation in 2D
    # 2. indexing and slicing in 2D
    # 3. basic operations in 2D
import numpy as np

In [4]:
# consider a list x with nested lists with equal size of same data type elements
x = [[1,2,3],[4,5,6],[7,8,9]]
X = np.array(x)
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# find no of dimension by .ndim property
X.ndim

2

In [6]:
# find no.of elements in each dimension use .shape
X.shape

(3, 3)

In [7]:
# get no.of elements in matrix using .size
X.size

9

In [8]:
# accessing elements
# X[rowInd][colInd]
X[0][1]

2

In [9]:
# slicing in 2D
X[0:2][0] # 0th colomn and row from 0 till before ele of 2nd ind

array([1, 2, 3])

In [10]:
X[1][0:2] # 1st row column 0 till before 2nd index of col

array([4, 5])

In [11]:
# vector addition
Y = np.array([[0,0,1],[1,1,0],[0,1,0]])
Z = X+Y

In [12]:
Z

array([[1, 2, 4],
       [5, 6, 6],
       [7, 9, 9]])

In [13]:
# multiplication of constant with vector
2*X

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [15]:
# multiplication of two vectors
A = X*Y
A

array([[0, 0, 3],
       [4, 5, 0],
       [0, 8, 0]])

In [20]:
# matrix multiplication A*B
# check if no.of columns of matrix A == no.of rows in matrix B
# in numpy dot product is similar to matrix multiplication
print(X,"\n\n",Y)
M = X.dot(Y)
M

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

 [[0 0 1]
 [1 1 0]
 [0 1 0]]


array([[ 2,  5,  1],
       [ 5, 11,  4],
       [ 8, 17,  7]])